import { createThemeContract } from '@vanilla-extract/css';

// Theme contract defines the structure of design tokens for multi-brand theming
export const themeContract = createThemeContract({
  color: {
    background: '',
    foreground: '',
    card: '',
    cardForeground: '',
    popover: '',
    popoverForeground: '',
    primary: '',
    primaryForeground: '',
    secondary: '',
    secondaryForeground: '',
    muted: '',
    mutedForeground: '',
    accent: '',
    accentForeground: '',
    destructive: '',
    destructiveForeground: '',
    border: '',
    input: '',
    ring: '',
    chart1: '',
    chart2: '',
    chart3: '',
    chart4: '',
    chart5: '',
    sidebar: '',
    sidebarForeground: '',
    sidebarPrimary: '',
    sidebarPrimaryForeground: '',
    sidebarAccent: '',
    sidebarAccentForeground: '',
    sidebarBorder: '',
    sidebarRing: '',
  },
  spacing: {
    0: '',
    px: '',
    0.5: '',
    1: '',
    1.5: '',
    2: '',
    2.5: '',
    3: '',
    3.5: '',
    4: '',
    5: '',
    6: '',
    7: '',
    8: '',
    9: '',
    10: '',
    11: '',
    12: '',
    14: '',
    16: '',
    20: '',
    24: '',
    28: '',
    32: '',
    36: '',
    40: '',
    44: '',
    48: '',
    52: '',
    56: '',
    60: '',
    64: '',
    72: '',
    80: '',
    96: '',
  },
  fontSize: {
    xs: '',
    sm: '',
    base: '',
    lg: '',
    xl: '',
    '2xl': '',
    '3xl': '',
    '4xl': '',
    '5xl': '',
    '6xl': '',
  },
  lineHeight: {
    none: '',
    tight: '',
    snug: '',
    normal: '',
    relaxed: '',
    loose: '',
  },
  fontWeight: {
    normal: '',
    medium: '',
    semibold: '',
    bold: '',
    extrabold: '',
  },
  borderRadius: {
    none: '',
    sm: '',
    base: '',
    md: '',
    lg: '',
    xl: '',
    '2xl': '',
    full: '',
  },
  shadow: {
    xs: '',
    sm: '',
    base: '',
    md: '',
    lg: '',
    xl: '',
    '2xl': '',
  },
  opacity: {
    0: '',
    50: '',
    80: '',
    90: '',
    100: '',
  },
  breakpoint: {
    sm: '',
    md: '',
    lg: '',
    xl: '',
    '2xl': '',
  },
});

export type Theme = typeof themeContract;
